# Generated by Django 2.1.5 on 2019-05-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userExtends', '0003_auto_20190526_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
