# Generated by Django 2.1.5 on 2019-05-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userExtends', '0005_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='in_area',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '강남구'), (2, '성동구'), (3, '영등포구'), (4, '광진구'), (5, '마포구'), (6, '송파구')], null=True, verbose_name='in_area'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='phone'),
        ),
    ]
