# Generated by Django 2.1.5 on 2019-05-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('mTotal', models.IntegerField()),
                ('fTotal', models.IntegerField()),
                ('area', models.CharField(choices=[('광진구', '광진구'), ('강남구', '강남구'), ('마포구', '마포구'), ('성동구', '성동구'), ('송파구', '송파구'), ('영등포구', '영등포구')], default='성동구', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
