# Generated by Django 2.1.7 on 2019-06-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='board',
            field=models.CharField(choices=[('공지사항', '공지사항'), ('문의사항', '문의사항'), ('프랜차이즈', '프랜차이즈'), ('창업정보나누기', '창업정보나누기'), ('창업계획서나누기', '창업계획서나누기')], default='공지사항', max_length=10),
        ),
    ]
