# Generated by Django 2.1.5 on 2019-06-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='author',
        ),
    ]
