# Generated by Django 2.1.5 on 2019-06-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20190614_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='author',
        ),
    ]
